# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitor', '0017_auto_20170314_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedAnalogItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_сode', models.CharField(blank=True, max_length=200)),
                ('article', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Category')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Store')),
            ],
        ),
        migrations.AddField(
            model_name='importedanalogitems',
            name='import_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adder.ImportItem'),
        ),
        migrations.AddField(
            model_name='importedanalogitems',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Store'),
        ),
    ]
