# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImportedAnalogItems',
            new_name='ImportedAnalogItem',
        ),
    ]
