# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adder', '0002_auto_20170421_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
