# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adder', '0003_importlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importlist',
            old_name='create_date',
            new_name='import_date',
        ),
    ]
