# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adder', '0004_auto_20170424_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='importitem',
            name='import_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adder.ImportList'),
        ),
    ]
