# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adder', '0006_importlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlist',
            name='comment',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
