# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalogItemsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Category')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_сode', models.CharField(max_length=200)),
                ('article', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('synonyms', models.CharField(blank=True, max_length=2000)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('img', models.FileField(blank=True, upload_to='item_img/%Y/%m/%d')),
                ('url', models.URLField(blank=True)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('analogs_items', models.ManyToManyField(blank=True, to='monitor.AnalogItemsGroup')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.City')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('logo', models.FileField(blank=True, upload_to='store_img/%Y/%m/%d')),
                ('url', models.URLField(blank=True)),
                ('city_cookie', models.CharField(blank=True, max_length=40)),
                ('city_select_metod', models.CharField(blank=True, choices=[('NO', ''), ('CO', 'Куки'), ('UR', 'URL')], default='NO', max_length=2)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.City')),
            ],
        ),
    ]
