# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_remove_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='analogs_items',
            field=models.ManyToManyField(blank=True, null=True, to='monitor.AnalogItemsGroup'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Category'),
        ),
    ]
