# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20170310_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='url_after',
            new_name='url_domain',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='url_before',
            new_name='url_folder',
        ),
    ]
