# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_auto_20170310_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='city_cookie',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
