# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_item_city_cookie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sap_сode',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
