# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_auto_20170310_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.URLField(blank=True),
        ),
    ]
