# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_auto_20170310_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='modify_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
