# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0021_auto_20170420_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='store',
            name='url',
        ),
    ]
