# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0022_auto_20170420_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterField(
            model_name='city',
            name='short_title',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='short_title',
            field=models.CharField(max_length=50),
        ),
    ]
